export const RESET_APP = 'RESET_APP';

export const RECIPES_SEARCHED = 'RECIPES_SEARCHED';
export const ALL_RECIPES_FETCHED = 'ALL_RECIPES_FETCHED';

export const ALL_FILTERS_FETCHED = 'ALL_FILTERS_FETCHED';
export const FILTER_ADDED = 'FILTER_ADDED';
export const FILTER_REMOVED = 'FILTER_REMOVED';
